name: bhlh_annotator
channels:
  - bioconda
  - defaults
dependencies:
  - blast=2.6.0
  - dendropy=4.6.0
  - fasttree=2.1.11
  - hmmer=3.3.2
  - mafft=7.520
  - matplotlib=3.7.1
  - muscle=5.1
  - numpy=1.24.3
  - pandas=1.5.3
  - python=3.11.3
  - raxml=8.2.12